name: test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run lint

  unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: npm i && npm i --prefix test/e2e/miniprogram-project && npm i --prefix test/e2e/plugin-project  && npx lerna bootstrap --no-ci

      - name: copy-webpack-plugin
        run: npm run copyPlugin --prefix test/e2e/miniprogram-project && npm run copyPlugin --prefix test/e2e/plugin-project

      - name: build-miniprogram
        run: npm run build:cross --prefix test/e2e/miniprogram-project

      - name: build-plugin
        run: npm run build --prefix test/e2e/plugin-project

      - name: exec unit test
        run: npm t && npm t --prefix test/e2e/miniprogram-project && npm t --prefix test/e2e/plugin-project
